version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - ${DB_PORT:-5434}:5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      args:
        PORT: 3000
    restart: always
    ports:
      - ${PORT:-3000}:3000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app?schema=public
      JWT_SECRET: change-me
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
